package com.ddas.sns.userphotogroup.mapper;

import com.ddas.sns.userphotogroup.domain.UserPhotoGroup;
import com.ddas.sns.userphotogroup.domain.UserPhotoGroupCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserPhotoGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_group
     *
     * @mbggenerated Mon Aug 15 23:21:16 CST 2016
     */
    int countByExample(UserPhotoGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_group
     *
     * @mbggenerated Mon Aug 15 23:21:16 CST 2016
     */
    int deleteByExample(UserPhotoGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_group
     *
     * @mbggenerated Mon Aug 15 23:21:16 CST 2016
     */
    int insert(UserPhotoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_group
     *
     * @mbggenerated Mon Aug 15 23:21:16 CST 2016
     */
    int insertSelective(UserPhotoGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_group
     *
     * @mbggenerated Mon Aug 15 23:21:16 CST 2016
     */
    List<UserPhotoGroup> selectByExample(UserPhotoGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_group
     *
     * @mbggenerated Mon Aug 15 23:21:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserPhotoGroup record, @Param("example") UserPhotoGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_photo_group
     *
     * @mbggenerated Mon Aug 15 23:21:16 CST 2016
     */
    int updateByExample(@Param("record") UserPhotoGroup record, @Param("example") UserPhotoGroupCriteria example);
}