package com.ddas.sns.mylog.domain;

import java.util.ArrayList;
import java.util.List;

public class MyLogInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    protected List<Criteria> oredCriteria;

    private int limitStart;

    private int limitEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public MyLogInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    public int getLimitStart() {
        return this.limitStart;
    }

    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    public int getLimitEnd() {
        return this.limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMyLogIdIsNull() {
            addCriterion("my_log_id is null");
            return (Criteria) this;
        }

        public Criteria andMyLogIdIsNotNull() {
            addCriterion("my_log_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyLogIdEqualTo(String value) {
            addCriterion("my_log_id =", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdNotEqualTo(String value) {
            addCriterion("my_log_id <>", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdGreaterThan(String value) {
            addCriterion("my_log_id >", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdGreaterThanOrEqualTo(String value) {
            addCriterion("my_log_id >=", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdLessThan(String value) {
            addCriterion("my_log_id <", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdLessThanOrEqualTo(String value) {
            addCriterion("my_log_id <=", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdLike(String value) {
            addCriterion("my_log_id like", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdNotLike(String value) {
            addCriterion("my_log_id not like", value, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdIn(List<String> values) {
            addCriterion("my_log_id in", values, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdNotIn(List<String> values) {
            addCriterion("my_log_id not in", values, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdBetween(String value1, String value2) {
            addCriterion("my_log_id between", value1, value2, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogIdNotBetween(String value1, String value2) {
            addCriterion("my_log_id not between", value1, value2, "myLogId");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleIsNull() {
            addCriterion("my_log_title is null");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleIsNotNull() {
            addCriterion("my_log_title is not null");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleEqualTo(String value) {
            addCriterion("my_log_title =", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleNotEqualTo(String value) {
            addCriterion("my_log_title <>", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleGreaterThan(String value) {
            addCriterion("my_log_title >", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleGreaterThanOrEqualTo(String value) {
            addCriterion("my_log_title >=", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleLessThan(String value) {
            addCriterion("my_log_title <", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleLessThanOrEqualTo(String value) {
            addCriterion("my_log_title <=", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleLike(String value) {
            addCriterion("my_log_title like", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleNotLike(String value) {
            addCriterion("my_log_title not like", value, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleIn(List<String> values) {
            addCriterion("my_log_title in", values, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleNotIn(List<String> values) {
            addCriterion("my_log_title not in", values, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleBetween(String value1, String value2) {
            addCriterion("my_log_title between", value1, value2, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTitleNotBetween(String value1, String value2) {
            addCriterion("my_log_title not between", value1, value2, "myLogTitle");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesIsNull() {
            addCriterion("my_log_types is null");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesIsNotNull() {
            addCriterion("my_log_types is not null");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesEqualTo(String value) {
            addCriterion("my_log_types =", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesNotEqualTo(String value) {
            addCriterion("my_log_types <>", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesGreaterThan(String value) {
            addCriterion("my_log_types >", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesGreaterThanOrEqualTo(String value) {
            addCriterion("my_log_types >=", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesLessThan(String value) {
            addCriterion("my_log_types <", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesLessThanOrEqualTo(String value) {
            addCriterion("my_log_types <=", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesLike(String value) {
            addCriterion("my_log_types like", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesNotLike(String value) {
            addCriterion("my_log_types not like", value, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesIn(List<String> values) {
            addCriterion("my_log_types in", values, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesNotIn(List<String> values) {
            addCriterion("my_log_types not in", values, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesBetween(String value1, String value2) {
            addCriterion("my_log_types between", value1, value2, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTypesNotBetween(String value1, String value2) {
            addCriterion("my_log_types not between", value1, value2, "myLogTypes");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsIsNull() {
            addCriterion("my_log_tags is null");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsIsNotNull() {
            addCriterion("my_log_tags is not null");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsEqualTo(String value) {
            addCriterion("my_log_tags =", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsNotEqualTo(String value) {
            addCriterion("my_log_tags <>", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsGreaterThan(String value) {
            addCriterion("my_log_tags >", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsGreaterThanOrEqualTo(String value) {
            addCriterion("my_log_tags >=", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsLessThan(String value) {
            addCriterion("my_log_tags <", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsLessThanOrEqualTo(String value) {
            addCriterion("my_log_tags <=", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsLike(String value) {
            addCriterion("my_log_tags like", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsNotLike(String value) {
            addCriterion("my_log_tags not like", value, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsIn(List<String> values) {
            addCriterion("my_log_tags in", values, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsNotIn(List<String> values) {
            addCriterion("my_log_tags not in", values, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsBetween(String value1, String value2) {
            addCriterion("my_log_tags between", value1, value2, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogTagsNotBetween(String value1, String value2) {
            addCriterion("my_log_tags not between", value1, value2, "myLogTags");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsIsNull() {
            addCriterion("my_log_privs is null");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsIsNotNull() {
            addCriterion("my_log_privs is not null");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsEqualTo(String value) {
            addCriterion("my_log_privs =", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsNotEqualTo(String value) {
            addCriterion("my_log_privs <>", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsGreaterThan(String value) {
            addCriterion("my_log_privs >", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsGreaterThanOrEqualTo(String value) {
            addCriterion("my_log_privs >=", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsLessThan(String value) {
            addCriterion("my_log_privs <", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsLessThanOrEqualTo(String value) {
            addCriterion("my_log_privs <=", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsLike(String value) {
            addCriterion("my_log_privs like", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsNotLike(String value) {
            addCriterion("my_log_privs not like", value, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsIn(List<String> values) {
            addCriterion("my_log_privs in", values, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsNotIn(List<String> values) {
            addCriterion("my_log_privs not in", values, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsBetween(String value1, String value2) {
            addCriterion("my_log_privs between", value1, value2, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogPrivsNotBetween(String value1, String value2) {
            addCriterion("my_log_privs not between", value1, value2, "myLogPrivs");
            return (Criteria) this;
        }

        public Criteria andMyLogContentIsNull() {
            addCriterion("my_log_content is null");
            return (Criteria) this;
        }

        public Criteria andMyLogContentIsNotNull() {
            addCriterion("my_log_content is not null");
            return (Criteria) this;
        }

        public Criteria andMyLogContentEqualTo(String value) {
            addCriterion("my_log_content =", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentNotEqualTo(String value) {
            addCriterion("my_log_content <>", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentGreaterThan(String value) {
            addCriterion("my_log_content >", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentGreaterThanOrEqualTo(String value) {
            addCriterion("my_log_content >=", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentLessThan(String value) {
            addCriterion("my_log_content <", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentLessThanOrEqualTo(String value) {
            addCriterion("my_log_content <=", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentLike(String value) {
            addCriterion("my_log_content like", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentNotLike(String value) {
            addCriterion("my_log_content not like", value, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentIn(List<String> values) {
            addCriterion("my_log_content in", values, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentNotIn(List<String> values) {
            addCriterion("my_log_content not in", values, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentBetween(String value1, String value2) {
            addCriterion("my_log_content between", value1, value2, "myLogContent");
            return (Criteria) this;
        }

        public Criteria andMyLogContentNotBetween(String value1, String value2) {
            addCriterion("my_log_content not between", value1, value2, "myLogContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_log
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 29 23:01:00 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andMyLogIdLikeInsensitive(String value) {
            addCriterion("upper(my_log_id) like", value.toUpperCase(), "myLogId");
            return this;
        }

        public Criteria andMyLogTitleLikeInsensitive(String value) {
            addCriterion("upper(my_log_title) like", value.toUpperCase(), "myLogTitle");
            return this;
        }

        public Criteria andMyLogTypesLikeInsensitive(String value) {
            addCriterion("upper(my_log_types) like", value.toUpperCase(), "myLogTypes");
            return this;
        }

        public Criteria andMyLogTagsLikeInsensitive(String value) {
            addCriterion("upper(my_log_tags) like", value.toUpperCase(), "myLogTags");
            return this;
        }

        public Criteria andMyLogPrivsLikeInsensitive(String value) {
            addCriterion("upper(my_log_privs) like", value.toUpperCase(), "myLogPrivs");
            return this;
        }

        public Criteria andMyLogContentLikeInsensitive(String value) {
            addCriterion("upper(my_log_content) like", value.toUpperCase(), "myLogContent");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}