package com.ddas.sns.mylog.domain;

import java.io.Serializable;

public class MyLogInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_log.my_log_id
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    private String myLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_log.my_log_title
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    private String myLogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_log.my_log_types
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    private String myLogTypes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_log.my_log_tags
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    private String myLogTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_log.my_log_privs
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    private String myLogPrivs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_log.my_log_content
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    private String myLogContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_log
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_log.my_log_id
     *
     * @return the value of my_log.my_log_id
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public String getMyLogId() {
        return myLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_log.my_log_id
     *
     * @param myLogId the value for my_log.my_log_id
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setMyLogId(String myLogId) {
        this.myLogId = myLogId == null ? null : myLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_log.my_log_title
     *
     * @return the value of my_log.my_log_title
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public String getMyLogTitle() {
        return myLogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_log.my_log_title
     *
     * @param myLogTitle the value for my_log.my_log_title
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setMyLogTitle(String myLogTitle) {
        this.myLogTitle = myLogTitle == null ? null : myLogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_log.my_log_types
     *
     * @return the value of my_log.my_log_types
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public String getMyLogTypes() {
        return myLogTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_log.my_log_types
     *
     * @param myLogTypes the value for my_log.my_log_types
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setMyLogTypes(String myLogTypes) {
        this.myLogTypes = myLogTypes == null ? null : myLogTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_log.my_log_tags
     *
     * @return the value of my_log.my_log_tags
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public String getMyLogTags() {
        return myLogTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_log.my_log_tags
     *
     * @param myLogTags the value for my_log.my_log_tags
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setMyLogTags(String myLogTags) {
        this.myLogTags = myLogTags == null ? null : myLogTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_log.my_log_privs
     *
     * @return the value of my_log.my_log_privs
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public String getMyLogPrivs() {
        return myLogPrivs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_log.my_log_privs
     *
     * @param myLogPrivs the value for my_log.my_log_privs
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setMyLogPrivs(String myLogPrivs) {
        this.myLogPrivs = myLogPrivs == null ? null : myLogPrivs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_log.my_log_content
     *
     * @return the value of my_log.my_log_content
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public String getMyLogContent() {
        return myLogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_log.my_log_content
     *
     * @param myLogContent the value for my_log.my_log_content
     *
     * @mbggenerated Wed Jun 29 23:01:00 CST 2016
     */
    public void setMyLogContent(String myLogContent) {
        this.myLogContent = myLogContent == null ? null : myLogContent.trim();
    }
}