package com.ddas.sns.vip.mapper;

import com.ddas.sns.vip.domain.VipRechargeRecords;
import com.ddas.sns.vip.domain.VipRechargeRecordsCriteria;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VipRechargeRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int countByExample(VipRechargeRecordsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int deleteByExample(VipRechargeRecordsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int deleteByPrimaryKey(String recordsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int insert(VipRechargeRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int insertSelective(VipRechargeRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    List<VipRechargeRecords> selectByExample(VipRechargeRecordsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    VipRechargeRecords selectByPrimaryKey(String recordsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int updateByExampleSelective(@Param("record") VipRechargeRecords record, @Param("example") VipRechargeRecordsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int updateByExample(@Param("record") VipRechargeRecords record, @Param("example") VipRechargeRecordsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int updateByPrimaryKeySelective(VipRechargeRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_records
     *
     * @mbggenerated Fri Aug 12 22:17:41 CST 2016
     */
    int updateByPrimaryKey(VipRechargeRecords record);
}