package com.ddas.sns.email.mapper;

import com.ddas.sns.email.domain.UserEmail;
import com.ddas.sns.email.domain.UserEmailCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_email
     *
     * @mbggenerated Tue Jul 12 23:01:07 CST 2016
     */
    int countByExample(UserEmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_email
     *
     * @mbggenerated Tue Jul 12 23:01:07 CST 2016
     */
    int deleteByExample(UserEmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_email
     *
     * @mbggenerated Tue Jul 12 23:01:07 CST 2016
     */
    int insert(UserEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_email
     *
     * @mbggenerated Tue Jul 12 23:01:07 CST 2016
     */
    int insertSelective(UserEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_email
     *
     * @mbggenerated Tue Jul 12 23:01:07 CST 2016
     */
    List<UserEmail> selectByExample(UserEmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_email
     *
     * @mbggenerated Tue Jul 12 23:01:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserEmail record, @Param("example") UserEmailCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_email
     *
     * @mbggenerated Tue Jul 12 23:01:07 CST 2016
     */
    int updateByExample(@Param("record") UserEmail record, @Param("example") UserEmailCriteria example);
}